### ISSUE TITLE
`/laodeai` handler: caniuse.com

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/bot#120]
use this as a test case: https://caniuse.com/css-grid

just add it into the handler lists, no need to think about how to call that handler. response might be only the supported device.

example response:
```
IE: partially supported
Edge: supported
Firefox: supported
Chrome: supported
Safari: supported
Opera: supported
Safari on iOS: supported
Opera Mini: not supported
Android Browser: supported
...
```

cc @elianiva

**Comment by elianiva** [comment]
might also display them as `Google Chrome: supported (starting from v69)` and maybe throw in some checkmark/cross emoji
