### ISSUE TITLE
New group poll doesn't updated to existing poll message

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/bot#164]
Let's say that at 1 PM, Andrew creates a poll on the group. The bot would catch the event and set a new message that contains the link to today's poll, and pin it. At 2 PM, Bobby creates a new poll on the group (note that this is on the same day), the bot caught the event, but it wouldn't update the existing message that is defined earlier with Bobby's poll. It **should** update the message that the bot created that contains the link to today's poll.

Try it yourself at the Teknologi Umum group.

Additional error log from Sentry: https://sentry.io/share/issue/bc40034287e74c989f1f506acd4b50f5/

**Comment by raji2004** [comment]
i would love to be assigned this
