### ISSUE TITLE
`/news` is broken

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/bot#165]
Error from Sentry: https://sentry.io/share/issue/7d6e0ebd0db24979abea658c9bbc5281/

```
TypeError: Cannot read properties of undefined (reading 'slice')

/app/src/services/news/index.js in <anonymous> at line 27:10

Called from: /app/src/services/news/index.js in runMicrotasks
/app/src/utils/cache.js in SingleValueCache.getOrCreate at line 53:22

/app/src/services/news/index.js in news at line 17:36

Called from: /app/node_modules/telegraf/lib/composer.js in execute
```

**Comment by Rounak-28** [comment]
@aldy505 Can I try to solve this error?

**Comment by aldy505** [comment]
@Rounak-28 sure go ahead

**Comment by sierraleonez** [comment]
No issue or exception in debug mode
![image](https://github.com/teknologi-umum/bot/assets/72799975/1534e57d-0e45-4fe2-a833-2baf3e03e902)

cURL to the [news API](https://berita-indo-api.vercel.app/v1/cnn-news) yields no error or exception
![image](https://github.com/teknologi-umum/bot/assets/72799975/c2c16fa7-15af-47e0-be03-37c37d912b88)

@aldy505

**Comment by aldy505** [comment]
I think it got fixed somewhere. Closing this issue for now.
