### ISSUE TITLE
`/qr` <url>

### ISSUE THREAD

**Issue by ronnygunawan** [teknologi-umum/bot#18]
```
/qr https://www.google.com/
```

- Generate QR code (jangan pakai API)
- Send QR code beserta linknya ke chat

**Comment by lamualfa** [comment]
Brilliant

**Comment by lamualfa** [comment]
https://github.com/soldair/node-qrcode

**Comment by aldy505** [comment]
@ronnygunawan latest commit (f6687c3e55457b8540ddfa694526483f8ef791b5) failed. logs:

```
import { QRCodeCanvas } from '@cheprasov/qrcode';
         ^^^^^^^^^^^^
SyntaxError: Named export 'QRCodeCanvas' not found. The requested module '@cheprasov/qrcode' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@cheprasov/qrcode';
const { QRCodeCanvas } = pkg;
```

Terus pas diubah jadi:
```js
import QRCode from '@cheprasov/qrcode';
const { QRCodeCanvas } = QRCode
```

Running command `/qr lorem ipsum`. Dapet error lagi:
```
ReferenceError: document is not defined
    at new e (/home/reinaldyrfl/repository/teknologi-umum/pinbot/node_modules/@cheprasov/qrcode/dist/qrcode.js:1:25162)
    at file:///home/reinaldyrfl/repository/teknologi-umum/pinbot/src/services/qr.js:16:24
    at /home/reinaldyrfl/repository/teknologi-umum/pinbot/node_modules/telegraf/lib/composer.js:158:111
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async execute (/home/reinaldyrfl/repository/teknologi-umum/pinbot/node_modules/telegraf/lib/composer.js:458:17)
    at async /home/reinaldyrfl/repository/teknologi-umum/pinbot/node_modules/telegraf/lib/composer.js:459:21
    at async execute (/home/reinaldyrfl/repository/teknologi-umum/pinbot/node_modules/telegraf/lib/composer.js:458:17)
    at async /home/reinaldyrfl/repository/teknologi-umum/pinbot/node_modules/telegraf/lib/composer.js:459:21
    at async execute (/home/reinaldyrfl/repository/teknologi-umum/pinbot/node_modules/telegraf/lib/composer.js:458:17)
    at async /home/reinaldyrfl/repository/teknologi-umum/pinbot/node_modules/telegraf/lib/composer.js:459:21
```

**Comment by aldy505** [comment]
Oh btw, kayaknya lebih baik pake ini:
```js
await context.telegram.sendPhoto(
  context.message.chat.id,
  qrCanvas.toDataUrl(),
  {
    caption: text,
    reply_to_message_id: message_id,
  },
);
```

daripada ini:
```js
await context.replyWithPhoto(
  {
    source: qrCanvas.toDataUrl(),
  },
  {
    caption: text,
    reply_to_message_id: message_id,
  },
);
```

**Comment by nblfikr** [comment]
saya berusaha menyelesaikan issue ini, tapi kesulitan saat sendPhoto

`const generateQR = async text => {
  try {
    return await QRCode.toDataURL(text)
  } catch (err) {
    console.error(err)
  }
}`

ini base64 hasil generate QR

`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHQAAAB0CAYAAABUmhYnAAAAAklEQVR4AewaftIAAAKwSURBVO3BQY6sCAwFwXwW979yTu3GKyQE1O+yHBE/WGMUa5RijVKsUYo1SrFGKdYoxRqlWKMUa5RijVKsUYo1SrFGKdYoxRrl4KYkfJNKl4QzKl0SOpUzSfgmlTuKNUqxRinWKAcPU3lSEv4SlScl4UnFGqVYoxRrlIOXJeEKlScloVN5UhKuUHlTsUYp1ijFGuXgx6l0SbgiCZ3KLyvWKMUapVijHPy4JKz/FWuUYo1SrFEOXqbyJpUuCZ1Kl4QnqfwlxRqlWKMUa5SDhyXhm5LQqXRJ6FS6JFyRhL+sWKMUa5RijRI/GCQJd6j8smKNUqxRijXKwU1J6FTOJOFNKl0SOpUuCV0SOpUzSehUuiRcoXJHsUYp1ijFGuXgYUnoVDqVM0noVLokdCpdEu5Q6ZLQqZxJQqfyTcUapVijFGuUg5tUziThjMqZJHQqXRLOqJxR6ZJwh8qZJJxRuaNYoxRrlGKNEj+4IQmdyhVJ6FTuSMIVKm9KwhUqdxRrlGKNUqxRDh6WhE6lS0Kn0iXhCpUrVK5IQqdyJgmdSpeENxVrlGKNUqxR4gc/LAlnVLoknFE5k4ROpUvCFSpPKtYoxRqlWKMc3JSEb1K5Q6VLQpeEK5LQqXRJ6FTeVKxRijVKsUY5eJjKk5JwhcqZJFyh0iXhTBKuSEKnckexRinWKMUa5eBlSbhC5Y4kdCpXqHRJOKPSJaFT6ZLwpmKNUqxRijXKwTAqT1I5k4ROpUtCp/KmYo1SrFGKNcrBj1M5k4RO5YokdCqdyhVJOKNyR7FGKdYoxRrl4GUqvyQJVyShU/mXijVKsUYp1igHD0vCNyXhiiR0Kp3KFSpXqLypWKMUa5RijRI/WGMUa5RijVKsUYo1SrFGKdYoxRqlWKMUa5RijVKsUYo1SrFGKdYoxRrlP7y4BPoJcSh+AAAAAElFTkSuQmCC`

dan ini cara kirimnya

`await context.telegram.sendPhoto(
    context.message.chat.id,
    await generateQR(query),
    {
      caption: query
    }
  );`

mohon bantuannya

**Comment by elianiva** [comment]
kalo udah kelar, langsung bikin PR aja

**Comment by aldy505** [comment]
#170
