### ISSUE TITLE
`/devread` command

### ISSUE THREAD

**Issue by artileda** [teknologi-umum/bot#19]
Pingin bikin link ya isinya kumpulan renungan untuk kamerad TU sekalian.

Gimana menurut maintainer sekalian?

@aldy505

**Comment by aldy505** [comment]
Boleh. Paling nanti datanya di store di database kan ya? Di repo private lain lagi disiapin sih buat bikin command `/dailyquiz`, nyambungnya nanti ke database mongo. Udah disiapin juga databasenya.

cc @elianiva @lamualfa
