### ISSUE TITLE
Upgrade to MongoDB 7

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/bot#216]
I got an email from MongoDB Cloud that says

> Your M0/M2/M5 Atlas cluster(s) will be automatically upgraded to MongoDB 7.0 in February 2024. 
>
> ## What’s in the update?
> [MongoDB 7.0](https://www.mongodb.com/blog/post/4-big-reasons-upgrade-mongodb-7-0) introduces new features and improvements such as:
>
> * [Compound wildcard indexes](https://www.mongodb.com/docs/manual/core/indexes/index-types/index-wildcard/index-wildcard-compound/) 
> * [New aggregation operators](https://www.mongodb.com/docs/manual/release-notes/7.0/#aggregation) such as $median and $percentile
> * [Queryable Encryption](https://www.mongodb.com/docs/v7.0/core/queryable-encryption/) (now Generally Available)
>
> ## What do I need to do?
> To ensure a seamless transition, we recommend updating your driver version to ensure continued compatibility with your applications. If your applications are compatible with MongoDB version 7.0, no downtime is expected for your applications. Visit our Docs to see [compatibility changes in 7.0](https://www.mongodb.com/docs/manual/release-notes/7.0-compatibility/), determine which [driver versions are compatible with 7.0](https://www.mongodb.com/docs/drivers/), and download the latest version.
>
> While most upgrades do not require any application changes, if you are concerned about compatibility we recommend exploring the [Stable API](https://www.mongodb.com/docs/manual/reference/stable-api/).

These are the parts that we need to look at:

https://github.com/teknologi-umum/bot/blob/513712570780fae2db2f60f46c2edef41f52a607/docker-compose.yml#L2-L3

https://github.com/teknologi-umum/bot/blob/513712570780fae2db2f60f46c2edef41f52a607/package.json#L37

https://github.com/teknologi-umum/bot/blob/513712570780fae2db2f60f46c2edef41f52a607/src/app.js#L49-L51

**Comment by WahidinAji** [comment]
https://github.com/teknologi-umum/bot/pull/226
