### ISSUE TITLE
`/laodeai` - our own github copilot clone

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/bot#22]
might search from:
- stackoverflow
- github gist
- quora
- google / duckduckgo / brave search

then sends the result

cc @ronnygunawan

**Comment by elianiva** [comment]
copilot bootleg

![image](https://user-images.githubusercontent.com/51877647/131594692-0e814bb2-1535-422d-9a34-23333f336195.png)

**Comment by aldy505** [comment]
done in #62
