### ISSUE TITLE
`/news`: Show 15 news from MSN Indonesia feed

### ISSUE THREAD

**Issue by ronnygunawan** [teknologi-umum/bot#79]
https://www.msn.com/id-id/berita

**Comment by aldy505** [comment]
bisa juga tambahin fitur: `/news <query>`

**Comment by elianiva** [comment]
> bisa juga tambahin fitur: /news <query>

ga bisa ini
gimana mau query, search barnya aja ngarah ke bing wkwk
hasilnya ga selalu berita, jadi sama aja kaya `/search`

**Comment by ronnygunawan** [comment]
Ok. MVP kita bisa pake ini dulu: https://newsapi.org/s/indonesia-news-api
100 requests per hari, jadi bisa cache pake cache.js per 30 menit

**Comment by elianiva** [comment]
API alternatif: https://github.com/satyawikananda/berita-indo-api
