### ISSUE TITLE
bug: Error: can't parse entities

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/bot#88]
Link to Sentry issues:
- https://sentry.io/share/issue/97a49e310ce145cab5342f72018948a1/
- https://sentry.io/share/issue/047208106eaf4df99378329c6e4b2711/

Occurred when doing these on a public supergroup:
- `/laodeai the art of productive laziness`
- `/search chrome download via blob`

A bit of help:
```
http      GET    https://en.wikipedia.org/wiki/Laziness [200] info 05:59:21
http      POST   https://api.telegram.org/-redacted-/sendMessage [400] info 05:59:21
exception Error: 400: Bad Request: can't parse entities: Unmatched end tag at byte offset 490, expected "</i>", found "</a>" error 05:59:21
```

```
http      GET    https://html.duckduckgo.com/html/?kp=1&q=chrome+download+via+blob [200] info 08:15:39
http      POST   https://api.telegram.org/-redacted-/sendMessage [400] info 08:15:39
exception Error: 400: Bad Request: can't parse entities: Unsupported start tag "script" at byte offset 1893 error 08:15:39
```

If you need more information, feel free to ask it here or in the Telegram group. Good luck.

**Comment by elianiva** [comment]
FWIW

yg pertama gara gara hasilnya invalid HTML, kelebihan `</a>` satu di akhir, not sure what to do about it

```html
<b>Laziness</b> (also known as <b>indolence</b>) is disinclination to activity or exertion despite having the ability to act or to
exert oneself. It is often used as a pejorative; terms for a person seen to be lazy
include <a href="/wiki/Sedentary_lifestyle"> "couch potato"</a>, "<a href="/wiki/Slacker">slacker</a>", and <a href="https://en.wiktionary.org/wiki/bludger"> "bludger"</a>. Related concepts include <i><a href="/wiki/Sloth_(deadly_sin)">sloth</a></i>, a Christian sin, and <i></a>...
See more on: https://en.wikipedia.org/wiki/Laziness
```

yg kedua.. ada tag `<script>` yg belom disanitize di titleny

```html
<a href="https://www.npmjs.com/package/downloadjs">downloadjs - npm | Simple global download function via <script> include</a>
```

**Comment by aldy505** [comment]
kepikiran. might try this later.

**Comment by aldy505** [comment]
I spent too much time on this, kayaknya ga jadi, graphene aja deh.

tadi kepikiran 2 opsi:
1. create our own html sanitizer that really sanitizes the result
2. tambahin `String.replace()` yang isinya regex nyari tag element selain allowed tags (`a|b|i|s|u|em|strong|strike|del|code|pre`), terus ya replace sama `&gt;` dan `&lt;`
